### ISSUE TITLE
Function list slowdown when looking at "Find result"

### ISSUE THREAD

**Issue by zhukovgreen** [jmarrec/notepad#1]
Hi,
I found the problem which makes me not use the function list. Once I am looking for something and getting a Find result screen bellow, I have a strong slowdown when selecting results of the search. It seems the notepad++ regenerate a function list each time I select new hit (match in my search).
![capture](https://cloud.githubusercontent.com/assets/10520003/8803925/e65408be-2fc9-11e5-9ea2-ca4c84b864a3.PNG)

**Comment by jmarrec** [comment]
Interesting, I've never had that problem. The only slowness I experience is when loading a very large file the first time.
I'll try with a large file tomorrow. How big is your idf?

**Comment by zhukovgreen** [comment]
Hi,
it is 4800 rows long

**Comment by jmarrec** [comment]
Arthem,

Sorry for the delay, I was swamped.

I see what you're saying. It does seem to reload the function list when using the find command and then clicking on one match to get there. I had never been bothered by it, but I think my computer may be faster than yours. I'm currently toying with an .idf that has 40,000 lines from a previous project and it's only taking about a second to reload.

This is an inner notepad++ behavior, so from my perspective there are no easy fixes for that, aside from **temporarily closing the Function list pane when you have to repeteadly use the find command to navigate**.

I'm opening an issue on the notepad++ project itself, see if they have a better solution.

**Comment by zhukovgreen** [comment]
Ok. Thanks for checking
