### ISSUE TITLE
Function list does not work with IDF file

### ISSUE THREAD

**Issue by magiuliani** [jmarrec/notepad#2]
Dear Julien Marrec,
I tried your tool for idf editing since it could help me a lot for daily modeling work but the function list does not work... look the scrren shoot, please.

![notepad_functionlist](https://cloud.githubusercontent.com/assets/5240336/15225244/e293ac78-187d-11e6-9303-8008797715ac.png)
I followed your procedure to modify notepad. The only part that is not very clear is the modification of the shortcut file since I'm not an expert of that. I just added a second macro without making other changes (look the picture below). Any errors?
![notepad_shortcut](https://cloud.githubusercontent.com/assets/5240336/15225572/40d3fd0a-187f-11e6-90b8-91f239b99820.png)

I use Eplu8.4 and notepad v6.9.1
The problem is present only on file.idf, if I open any other file the function list works..

any suggestions will be appreciated
Marco

**Comment by jmarrec** [comment]
The function list has nothing to do with the code folding macro.

What you need is to edit (or replace) the `%appdata%/notepad++/functionList.xml`. As stated in the readme file (front page of this github), the easiest is to just get the one located in eQuest and EnergyPlus folder and to replace your local one. Here's the direct link to the [functionList.xml](https://raw.githubusercontent.com/jmarrec/notepad/master/eQuest%20and%20EnergyPlus/functionList.xml)

**Comment by magiuliani** [comment]
I did exactly what you suggest... any other suggestions?
I look inside the notepadd++ documentation and it seems that there are some issues with the configuration of functionList file for custom application. New versions of NP++ are different from previous ones. 
Which version of NP++ do you use?

**Comment by magiuliani** [comment]
Dear Julien, I tried to understand a little more of functionList but I'm not a notepad programmer. It seems that there are some issue with FunctionList plugin and some work is going on  developing version 2.0 and 2.1. They said that occasionally those versions could crash.. 
Could you please specify also which version of functionList do you use? V1.2?

**Comment by magiuliani** [comment]
After some googling today I found that functionList was including into notepad base files in version V6.5 so the issue releated to the plugin should be solved.
I don't understand why functionList does not work... there is any way to debugging whats going on?

 I tried also E+ file V7.1 and the problem is present also there, therefore is not depended from idf file. Is possible that there are some error in your code or the code is not compatible with the last version of NP++. Please let me know with version of NP do you use.

**Comment by magiuliani** [comment]
After some googling today I found that functionList was including into notepad base files in version V6.5 so the issue releated to the plugin should be solved.
I don't understand why functionList does not work... there is any way to debugging whats going on?

 I tried also E+ file V7.1 and the problem is present also there, therefore is not depended from idf file. Is possible that there are some error in your code or the code is not compatible with the last version of NP++. Please let me know with version of NP do you use.

**Comment by magiuliani** [comment]
My last commnets is that your old version of energyplus_class works.. I don't know if could be of any help.

**Comment by jmarrec** [comment]
I just download notepad++ v6.9.1 on another computer, loaded the 8-5 example file `1ZoneDataCenterCRAC_wPumpedDXCoolingCoil.idf` after saving it as "Sorted" from the IDF editor. Everything works as expected.

Are you sure you read all of the instructions correctly? You need to download the **raw** functionList.xml (direct link [here](https://raw.githubusercontent.com/jmarrec/notepad/master/eQuest%20and%20EnergyPlus/functionList.xml)), and **you need to use the "Sorted" option from the IDF editor** before saving.

Try to load [this file](https://drive.google.com/file/d/0B6iX99bTtTWxbVZGSTFXV0dmdTg/view?usp=sharing) and see if it works.

**Comment by magiuliani** [comment]
Dear Julien, now it is working correctly. I didn't save with "sorted" option !!
Many thanks for your quick replay and for the very good tool you have shared.

**Comment by jmarrec** [comment]
Ok glad it's not something more serious.

For the record the reason you have to use the sorted option is because I use regular expressions to find first the class of objects ( ALL OBJECTS IN CLASS: XXX) and then I parse everything in between so they are displayed under the right class.
