### ISSUE TITLE
Suggestions for Mac Users?

### ISSUE THREAD

**Issue by anchapin** [jmarrec/notepad#5]
My work laptop is a Mac and I just noticed that Notepad++ isn't available on Mac. Do you know if I can recreate what you are doing here in a tool that is available for Mac? Also, should I try Wine or a VM to run Notepad++ on Mac? I found this [article](https://setapp.com/how-to/alternative-to-notepad++-for-mac) with suggestions on alternatives to N++ on Mac or running it with an emulator or VM.

**Comment by jmarrec** [comment]
Just for posterity:

You should be able to find some extensions for VSCode highlighting for eg.
Or vim.

I think there was an electron one too.
